---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bunnjxpm/shadowmistress.com/
    - /bin/cp --verbose index.html $DEPLOYPATH
    - /bin/cp --verbose styles.css $DEPLOYPATH
    - /bin/cp --verbose script.js $DEPLOYPATH